### ISSUE TITLE
Toolbar menu dropdown gets obscured behind an adjacent toolbar

### ISSUE THREAD

**Issue by brentkeller** [DevResults/cevitxe#21]
I observed this with the known document IDs dropdown on the grid example.

<img width="476" alt="000008" src="https://user-images.githubusercontent.com/467397/62971720-7da80c80-bde0-11e9-8b43-dcfe721df323.png">
I tried setting `zIndex: 100` for the toolbar `menu` method but it doesn't seem to help. It looks like it's an ordering thing that I wasn't able to get past in a couple of mins.

**Comment by HerbCaudill** [comment]
fixed in 1f863e7
