### ISSUE TITLE
Peers don't get notified when a document is removed from a DocSet

### ISSUE THREAD

**Issue by brentkeller** [DevResults/cevitxe#23]
We don't have any way for `DocSetSync` to communicate to peers that `DocSet.removeDoc` has been called. For now we're just removing the removed doc's ID from the collection index so it's effectively ignored but this doesn't help reduce the size of the state and it probably doesn't work at all for non-collection documents.

I suspect we might need to update `DocSet.removeDoc` to call the handlers with `undefined` as the new doc so they can appropriately handle the removal of the document. We might get more clarity on this if we hear anything back on my automerge PR: [#210](https://github.com/automerge/automerge/pull/210)

**Comment by HerbCaudill** [comment]
the new Repo class handles this correctly
