### ISSUE TITLE
Simplify API for working with a single state document?

### ISSUE THREAD

**Issue by HerbCaudill** [DevResults/cevitxe#40]
In the Todo example, our entire state fits easily in a single document, and the Repo API feels really cumbersome.

- You have to put your state in a root-level document: instead of https://github.com/DevResults/cevitxe/blob/b34789110b10bcc1c83d4952b9a9a360550a64df/packages/examples/todo/src/redux/store.ts#L6-L10  you have to do this https://github.com/DevResults/cevitxe/blob/117ca3b0161dfcbe1a55849242afcac20b7ea1f0/packages/examples/todo/src/redux/store.ts#L6-L12

- Reducers have to return a dictionary of change functions that work on individual documents, instead of a single function that works on the entire repo state: this https://github.com/DevResults/cevitxe/blob/117ca3b0161dfcbe1a55849242afcac20b7ea1f0/packages/examples/todo/src/redux/reducers.ts#L11-L19 instead of this https://github.com/DevResults/cevitxe/blob/b34789110b10bcc1c83d4952b9a9a360550a64df/packages/examples/todo/src/redux/reducers.ts#L18-L24

- Same deal with selectors and anything else that cares about the shape of the overall state: You have to file everything inside this bogus `root` property. 

Do we care? If so, I wonder how we can simplify this use case? 

One idea I had was to accept reducers that return a single function instead of a dictionary of functions. When initializing the StoreManager, we could then check the shape of the proxyreducer we're passed, and if it returns single functions then go into "single-document mode" where we take care of putting things in the `root` document, and just exposing that document as the store's state, so the developer can deal with this as if there was just one document.

**Comment by diegose** [comment]
> we could then check the shape of the proxyreducer we're passed, and if it returns single functions then go into "single-document mode"

Is that possible? If so, would it be the most intuitive and discoverable possibility?

I agree that we need a single-doc version of this, but I'd probably make the separation explicit at the type system level (maybe that's what you were suggesting?)

**Comment by HerbCaudill** [comment]
> Is that possible?

It's definitely possible at runtime to tell the difference between a function and a dictionary of functions - is that what you meant?

> would it be the most intuitive and discoverable possibility?

It's the way a garden-variety Redux reducer works, so in that respect it would be intuitive.

**Comment by diegose** [comment]
> It's definitely possible at runtime to tell the difference between a function and a dictionary of functions - is that what you meant?

Oh, I get it. You would change the _return type_ of `ProxyReducer`:

```typescript
export type ProxyReducer = (state: any, action: AnyAction) =>
  ChangeMap | A.ChangeFn<any> | symbol | null
```

or maybe:
```typescript
export type MultiDocProxyReducer = (state: any, action: AnyAction) => ChangeMap | null
export type SingleDocProxyReducer = (state: any, action: AnyAction) => A.ChangeFn<any> | symbol
```

I prefer the latter, but in any case it's the same thing at runtime.

**Comment by HerbCaudill** [comment]
> Oh, I get it. You would change the _return type_ of `ProxyReducer`:

yup, sorry that wasn't clear

**Comment by HerbCaudill** [comment]
closing in favor of #49
